### PR TITLE
Fix issues in the Feb update

### LINKED ISSUE #406: Misaligned arrows when creating infinite arrow using equals sign
# Environment

```none
Cascadia Code version number: 2102.03
Application (with version) used to display text: Windows Terminal Preview 1.6.10412.0
OS platform and version: Win10 x64 20H2 19042.804
Screen resolution (i.e. 220dpi): 1920x1080, not sure about dpi

Any other software? Happens in Notepad++ v7.9. Also tested Cascadia Code PL 2102.03 with same results.
```

# Steps to reproduce

Add arrows with double angle brackets << or >> while drawing infinite arrows using equals signs ==
The segment with the arrows will appear vertically misaligned vis-à-vis the arrow shaft if the arrows are in the middle of the line body. 

E.g., the double arrows in this will appear to be a pixel or two below the rest of the arrow body:
<====<<====>>====|

# Expected behavior

Presumably the arrow will line up correctly with the rest of the line body.

# Actual behavior

The details of the misalignment (direction and pixel offset) vary depending on the font size. It's almost invisible at 14 point font, but particularly bad at 13. It seems to be perfect at a font size of 22. All other sizes I tested show it.

The effect does not seem to be present when using single angle bracket arrows < and >, and it doesn't seem to appear when using single or double angle brackets on a line made of minus symbols ----

Screenshot showing the behavior (Terminal Preview, Cascadia Code PL, font size 13):
image
It looks like the double arrow portions are a few pixels below the rest of the line.

Another screenshot, zoomed in (as above, but font size 16):
image
In this example, they're both above and below, but in different amounts depending on which direction the arrows are facing.

### LINKED ISSUE #408: Wrong design for U+2262
Version 2102.03

The Mathematical Operator U+2262 NOT IDENTICAL TO has four horizontal lines, similar to U+2263 STRICTLY EQUIVALENT TO. It should have three horizontal lines, similar to U+2261 IDENTICAL TO.

### LINKED ISSUE #412: `locl` features that swap 2 glyphs for 1 glyph
Opening a bug here for me to remember.

In the Dutch `locl` feature, there are substitutions to access ijacute forms:
```
sub iacute j by iacute_j.loclNLD;
sub Iacute J by Iacute_J.loclNLD;
``` 
Generally it is not ideal to substitute two user-entered glyphs for a single glyph in a monospace coding environment. A better implementation here is: `sub iacute j' by jacute`. This will mean removal of the `loclNLD` glyph mentioned above, and addition of `jacute`. 

In Catalan there are substitutions to access the `Ŀ` and `ŀ`:
```
sub  l' periodcentered' l by ldot;
sub  L' periodcentered' L by Ldot;
```
While this is a standard way to access the `Ŀ` and `ŀ`, I think that in this case it would make more sense to remove these substitutions and just leave the glyphs to look like `l·l`. These are atomic characters which can be accessed directly.

### LINKED ISSUE #414: Small gaps are visible in new arrow ligatures in the Konsole terminal emulator
# Environment

```none
Cascadia Code version number: 2102.003
Application (with version) used to display text: konsole 20.08.2
Font size: 11pt
Font variant: Cascadia Code Roman
OS: Pop!_OS 20.10
with Linux 5.8.0-7642-generic and GNOME 3.38.3
Screen resolution (i.e. 220dpi): 1920px×1080px
apparently 344mm×194mm (96x96dpi) according to xrandr and xdpyinfo
UI Scaling: 100%
Hinting setting: Slight (changed & reset recently)
Antialiasing: Standard (changed & reset recently)
Further settings: Large fonts accessibility option is enabled
```

# Steps to reproduce

Get the terminal to render a combining arrow ligature

# Expected behavior

Dashes / equal signs join exactly

# Actual behavior

Small gaps

# Screenshot

Screenshot from 2021-02-14 22-21-41

### LINKED ISSUE #415: Ḵ, Ḻ, Ṉ, Ṯ, ḵ, ḻ, ṉ have a macron below not an underline
# Environment

```none
Cascadia Code version number: 2102.03
Application (with version) used to display text: any
OS platform and version: any
Screen resolution (i.e. 220dpi):  any
```

# Steps to reproduce

Use Ḵ, Ḻ, Ṉ, Ṯ, ḵ, ḻ, ṉ  in any sequence like ḴḺṈṮḵḻṉ.

# Expected behavior

The macron below should not be as wide as the advance width.
It should be like the macron above in ĀĒĪŌṒṐŪȲӢӮ āēīōṓṑūȳӣӯ.

Screenshot 2021-02-14 at 23 12 01

# Actual behavior

The macron below is as wide as the advance width in each, causing it to connect when any of these is repeated or next to another of that set.

Screenshot 2021-02-14 at 23 09 36

The Glyphs.app glyph names of those glyphs come from the Unicode names of the characters for example Ḵ, 1E34, is 
LATIN CAPITAL LETTER K WITH LINE BELOW. But their canonical decomposition uses 0331 COMBINING MACRON BELOW instead of 0332 COMBINING LOW LINE, for example 1E34 is canonically equivalent to ≡ 004B 0331. The [Unicode charts for the Latin Extended Additional Block](https://www.unicode.org/charts/PDF/U1E00.pdf) has the note “*In this block the names "WITH LINE BELOW" refer to a macron below the letter*.”

0332 COMBINING LOW LINE has the following note in the [Unicode charts for the Combining Diachritics Block](https://www.unicode.org/charts/PDF/U0300.pdf):
```
= underline, underscore
• connects on left and right
```

0332 COMBINING LOW LINE "connects on left and right" but 0331 COMBINING MACRON BELOW doesn't. Neither should the macron below in those glyphs.

In practice, the macron below or the macron above can have various widths depending on what letter they are on (narrower on the i, wider on the m), but this is less common and is even less necessary with monospace fonts.

### LINKED ISSUE #416: Documentation: Update IntelliJ IDEA Setup Instructions
For some reason, IntelliJ IDEA *(v2020.3.2)* does not recognize the fonts directory on Windows (10), so Cascadia Code will not show up by default in the font selection after default font installation.

A workaround which worked for me is to put the TFT-Files into the fonts directory of the IntelliJ IDEA installation, which is defaultly at the following path:
```
C:\Program Files\JetBrains\IntelliJ IDEA Community Edition 2020.3.2\jbr\lib\fonts
```

It would be really nice if this would be added to the [Installation Instructions for IntelliJ](https://github.com/microsoft/cascadia-code/wiki/Installing-Cascadia-Code#setting-cascadia-code-in-intellij-ide-2019) in the Wiki Page.

### LINKED ISSUE #428: Remove MVAR table
Per [this thread](https://github.com/google/fonts/issues/2085), the addition of the MVAR table can cause an unwanted impact on vertical metrics / positioning due to inconsistent support. Unfortunately, this is necessary for the strikeout size and underline size modifications. This will roll-back #395.

### PR DESCRIPTION
**Pull request by aaronbell**
## Summary of the Pull Request

A small set of fixes that resolves a couple of new bugs introduced in the latest version, plus other fixes I have been working on. 

## PR Checklist
* [x] Closes #406 - updated anchor type to lock with the other equals-related ligatures
* [x] Closes #408 - corrected component used for glyph to align with Unicode
* [x] Closes #412 - updated locl features removing iacute_j ligature and Catalan substitution
* [x] Closes #414 - increased overlaps of middle glyph for arrow ligatures
* [x] Closes #415 - reduces width of macronbelow
* [x] Closes #416 - rolls back name ID 4 modification as JetBrains cannot process it correctly
* [x] Closes #428 - rolls back variation of the underline to prevent MVAR table generation

## Detailed Description of the Pull Request / Additional comments

Full changelist:
- Repositioned tilde in related ligatures. Previously it was higher than the standard one.
- Added missing vietnamese anchors on acute and grave (futureproofing). 
- Corrected / made consistent greater & less positioning in </> and <$> related ligatures.
- Otherwise reviewed hinting

### CODE REVIEW

**Comment by aaronbell** [comment]
Adding a few more updates :)

**Comment by DHowett** [comment]
@aaronbell this good for release soon? I'm happy to review/sign off and tag it 2102.23 if so :)

**Comment by aaronbell** [comment]
@DHowett the only other thing that might be worth doing is the postscript name issue I emailed you about a little while ago. Did you have thoughts on that?

**Comment by aaronbell** [comment]
@DHowett I've submitted another couple of small fixes to resolve the postscript issue and prevent the MVAR table generation. Should be good to go.

**Comment by DHowett** [comment]
Thanks! I'll build this into the next version of Terminal. Unfortunately, I missed the boat for this one by just a hair, so I'll hold back just a little while to avoid breaking people.

I have GOT to get Cascadia out of our package. Good lord.

**Comment by aaronbell** [comment]
@DHowett It'd probably be good—I think you can set up the packages such that the Windows Terminal one will automatically download a "Cascadia Code" one. 

That way we could also put the PL fonts in too, no? Then folks wouldn't have to download them separately!

**Review by DHowett — APPROVED** [review]

**Comment by DHowett** [comment]
@aaronbell whoops, ufolint got real mad about this. I also fixed the PR trigger so it would fail future PRs for linting errors.

> 2021-02-25T20:00:28.8261060Z Test result that led to failure:
> 2021-02-25T20:00:28.8365140Z [FAIL] sources/CascadiaCode-Bold.ufo/glyphs.public.background contains rogue files not listed in contents.plist: gheupturn-cy.glif, asciitilde_equal.liga.glif, less_less_equal_start.seq.glif, quotedblbase.glif, g.glif, less_less_equal_middle.seq.glif, parenleft_asterisk.liga.glif, ka-cy.glif, kaiS_ymbol.glif, A_lpha-latin.glif, idotless.glif, dcaron.alt.glif, G_stroke.glif, N_hookleft.glif, greater_greater_hyphen_middle.seq.glif, kappa.glif, numbersign_underscore_parenleft.liga.glif, greater_greater_equal_start.seq.glif, quoteright.glif, nine.glif, quotesinglbase.glif, d.glif, greater_greater_equal_middle.seq.glif, quoteleft.glif, p.glif, greater.center.glif, numbersign_middle.seq.glif, less_less_hyphen_middle.seq.glif, rho.glif, less_less_hyphen_start.seq.glif, greater_greater_hyphen_end.seq.glif, six.glif, onehalf.glif, K_aiS_ymbol.glif, nhookleft.glif, asterisk_parenright.liga.glif, greater_greater_equal_end.seq.glif, less_less_hyphen_end.seq.glif, greater.alt.glif, less_less_equal_end.seq.glif, notedbl-musical.glif, kadescender-cy.glif, degree.glif, dashdownA_rrow.glif, integraltp.glif, integralbt.glif

This seems like a very much not good thing? Are these dead old files that got moved and replaced? I noticed some things got moved out of `background` into `public` but didn't know enough to ask.

**Comment by DHowett** [comment]
I suspect that the files in the `background/` directory are outdated and should have been deleted because in the previous update you moved them into the non-`background` one?

**Comment by aaronbell** [comment]
Yeah, all those files (and the folders themselves I think) can just be deleted. No background files necessary!

**Comment by DHowett** [comment]
Whoa, none? The background contents file still refers to one thing: macronbelowcomb.

**Comment by aaronbell** [comment]
The background files have no impact on the font output. They're just there as extra cruft from my development work. I should really just delete them all on conversion to UFO.

**Comment by DHowett** [comment]
Mind doing that in a PR? I'm strapped into meetings almost all day ☹️

**Comment by aaronbell** [comment]
Oh... I merged the fix in :)

**Comment by DHowett** [comment]
huh, it notified me that your PR was closed (without merging)

**Comment by aaronbell** [comment]
Oh yeah, I PR'd the wrong thing, so closed it. Ended up just merging in an update directly. :x

**Comment by aaronbell** [comment]
(https://github.com/microsoft/cascadia-code/commit/d4fac8bb485279aaa6633f7bf00f3b56d2362e08)

**Comment by DHowett** [comment]
☹️ 

```
2021-02-25T20:23:08.8372820Z ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
2021-02-25T20:23:08.8418550Z sources/CascadiaCode-Bold.ufo
2021-02-25T20:23:08.8519700Z ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
2021-02-25T20:23:08.8621680Z  
2021-02-25T20:23:08.8723270Z [UFO directory] ....... 
2021-02-25T20:23:08.8819450Z    Found UFO v3
2021-02-25T20:23:08.8841710Z    Detected glyphs directories: 
2021-02-25T20:23:08.8843730Z      -- glyphs . 
2021-02-25T20:23:08.8845470Z      -- glyphs.public.background F
2021-02-25T20:23:08.8846400Z 
2021-02-25T20:23:08.8847740Z =============================================================================
2021-02-25T20:23:08.8849980Z sources/CascadiaCode-Bold.ufo failed ufolint testing! Exit with status code 1
2021-02-25T20:23:08.8851490Z =============================================================================
2021-02-25T20:23:08.8952800Z  
2021-02-25T20:23:08.9017690Z Test result that led to failure:
2021-02-25T20:23:08.9119990Z [FAIL] Unable to find the UFO directory 'glyphs.public.background' defined in layercontents.plist
2021-02-25T20:23:08.9219570Z  
```

**Comment by aaronbell** [comment]
Well that serves me right.

**Comment by aaronbell** [comment]
OK. updated again. Double-checked that it builds. :)

**Pull request merged**
