### PR TITLE
Correct mark positioning for Salishan

### PR DESCRIPTION
**Pull request by aaronbell**
## Summary of the Pull Request

Properly adds the new marks required for Salishan to the GDEF feature for marks. (Thanks to Timothy Montler for catching this) 

## PR Checklist
* [x] CLA signed.

## Detailed Description of the Pull Request / Additional comments

The special feature files that override as part of the font building process weren't updated properly to include the new diacritical marks, so they were not being aligned properly. This has now been corrected. 

## Before (if applicable) and After Images of the Character(s)
Screen Shot 2020-09-21 at 10 02 34 AM
top - current
bottom - corrected

### CODE REVIEW

**Comment by DHowett** [comment]
Mind bumping the version as well? 2009.21 should suffice :smile:

**Comment by DHowett** [comment]
(and i guess, it'll need a new FONTLOG entry)

**Comment by aaronbell** [comment]
You got it!

**Review by DHowett — APPROVED** [review]

**Comment by DHowett** [comment]
Thanks :)

**Comment by DHowett** [comment]
Since we're really close to a Terminal release, I should ask-

Should we release this as 2009.21? Or should we hang back a bit, if you've got more fixes coming?

**Comment by aaronbell** [comment]
I think we can push this out as 2009.21. I don't have any additional changes planned at this time :)

**Pull request merged**
