### PR TITLE
Fix casing in build paths for feature files

### PR DESCRIPTION
**Pull request by madig**
## Summary of the Pull Request

Make some paths in build.py case-exact because Linux filesystems tend to be case-sensitive.

## PR Checklist
* [ ] Closes #xxx
* [x] CLA signed. If not, go over [here](https://cla.opensource.microsoft.com/microsoft/Terminal) and sign the CLA
* [ ] Requires FONTLOG.txt to be updated
* [ ] Requires [/images/cascadia-code.png](/microsoft/cascadia-code/blob/master/images/cascadia-code.png) and/or [/images/cascadia-code-characters.png](/microsoft/cascadia-code/blob/master/images/cascadia-code-characters.png) to be updated
* [ ] I've discussed this with core contributors already. If not checked, I'm ready to accept this work might be rejected in favor of a different grand plan.

## Validation Steps Performed

Local build.

### CODE REVIEW

**Comment by madig** [comment]
Me thinks a GitHub Actions thing might be interesting? Or maybe not because the work happens so infrequently?

**Comment by madig** [comment]
DUH. I forgot to build the statics why blow up of course.

**Comment by madig** [comment]
@DHowett what happened to the GitHub Actions thing? Did someone turn it off for PRs? I do see jobs on https://github.com/microsoft/cascadia-code/actions though?!

**Comment by DHowett** [comment]
That's a very good question. We may have simply misconfigured it :smile:

It looks like the action is set to run on `push`; should we expand that?

**Comment by madig** [comment]
It seems to work for PRs now, thanks. Weird, I copy-pasted that `on:` directive from the GHA examples. Oh well.

**Pull request merged**
