### PR TITLE
Fix the typo metrics and hhea, set line gap to 0

### PR DESCRIPTION
**Pull request by aaronbell**
## Summary of the Pull Request

This change modifies the font vertical metrics for better consistency cross-platform. Block drawing characters adjusted to account for new metrics. 

## PR Checklist
* [x] CLA signed.
* [x] I've discussed this with core contributors already. 

## Detailed Description of the Pull Request / Additional comments
- Font metrics updated following the method used by [Google Fonts](https://github.com/googlefonts/gf-docs/tree/master/Spec#cjk-vertical-metrics)
- Block drawing characters also modified to account for the changed metrics and ensure overlaps in vertical lines. 
- Other Glyphs specific code removed from the UFO.

## Validation Steps Performed
Updated font reviewed in various coding environments, and hinting verified as not impacted.

### CODE REVIEW

**Comment by DHowett-MSFT** [comment]
Curious about having this in the build script instead of the font info. Is this so that we apply it to the PL and NF variants too?

**Comment by DHowett-MSFT** [comment]
Er, sorry, phone autocorrect. The `fontinfo.plist`

**Comment by aaronbell** [comment]
Hm. I put it in the build file since I figured that would override anything else. Not that I'm expecting the PL and NF variants to impact these, but better to be safe.

**Comment by DHowett-MSFT** [comment]
This is excellent, and Michael tested it with the terminal changes. Thanks for bearing with us. :smile:

**Comment by DHowett-MSFT** [comment]
@madig did we invalidate your blue zones by updating the metrics here? I just realized when I was archiving the 2004.30 release that we may need to circle back :smile:

**Comment by aaronbell** [comment]
I don't think it will! The glyph designs haven't changed, so the blue zones should still be good.

**Comment by DHowett-MSFT** [comment]
It looked like some of the blue zone numbers were based on ascent/descent, so I figured I'd ask

**Comment by madig** [comment]
Blue zones fortunately are entirely glyph design based and have nothing to do with line metrics😊

**Comment by DHowett-MSFT** [comment]
That’s excellent news. Thanks!

**Comment by madig** [comment]
Here's some blue (and green) zones for your viewing pleasure:
image
They include ascent/descent because the design does 😊

**Comment by DHowett-MSFT** [comment]
Well, I know what I'm going to be spending my Thursday learning about! Thanks :D

**Comment by madig** [comment]
It's a highly esoteric subject requiring arcane knowledge of the Postscript Type1 arts. FreeType renders this stuff _so nicely_, though. As a Microsoft person, you should stack up on exorcism equipment before you venture forth.

See e.g. https://glyphsapp.com/tutorials/hinting-postscript-autohinting and https://www.youtube.com/watch?v=9lABav9oM8E.

**Comment by aaronbell** [comment]
Speaking of arcane knowledge, I assume you've read [Raster Tragedy](http://rastertragedy.com/)?

**Comment by madig** [comment]
I skimmed it years ago and decided to that I prefer light hinting like FreeType does with CFFs and the light autohinter. :)

**Pull request merged**
