### PR TITLE
Updating Cascadia Code

### LINKED ISSUE #11: Add box-drawing and block element glyphs
The entire range of [box drawing](https://en.wikipedia.org/wiki/Box_Drawing_(Unicode_block)) (`U+2500 - U+257F`) and [block element](https://en.wikipedia.org/wiki/Block_Elements) (`U+2580 - U+259F`) characters is not covered by the font.

### LINKED ISSUE #29: /> tag doesn't look balanced
As of now the */>* tag looks like this

image

Same issue with Fira Code Retina font.

It looks unbalanced. Can you please fix this?

### LINKED ISSUE #36: Bug Report - missing glyphs for symbols like 'tick'
# Environment

```none
Cascadia Code version number: 1909.16
Application (with version) used to display text: PowerShell Core Terminal, Command Prompt
OS platform and version: Win10 Pro 1908 build 18363.356
Screen resolution (i.e. 220dpi): 1920*1080 15.6" 125% 

Any other software? Flutter SDK
```

# Steps to reproduce

* Run PowerShell Core terminal/Command Prompt from context menu
* Change font to Cascadia Code
* Run `flutter doctor`

# Expected behavior

With Fira Code
fira-code-working-glyph

# Actual behavior

With Cascadia code 

on PowerShell
cascadia-code-missing-glyph

on Command Prompt
cascadia-code-missing-glyph-2

Missing glyphs can be seen above as empty boxes

### LINKED ISSUE #46: == ligature
The distinction between "=" and "==" is quite subtle which could be dangerous for c++ code, maybe a 3 line equals for the "==" ligature could be more appropriate?

### LINKED ISSUE #62: En dash showing in PowerShell directory listings in Windows Terminal
# Environment

```none
Cascadia Code version number: 1909.16
Application (with version) used to display text: Windows Terminal (Preview) v0.4.2382.0
OS platform and version: Windows 10 Pro 10.0.18362 N/A Build 18362
Screen resolution (i.e. 220dpi): 3840 x 2160 / 125% scale
```

# Steps to reproduce

Display the contents of a directory in PowerShell:

```
> dir
```

# Expected behavior

The Mode should be displayed with all hyphens:

d-----
-a----

# Actual behavior

The character after the letter (and before in the case of a) is an en dash instead of a hyphen:

image

The en dash is also slightly lower than the hyphen.

### LINKED ISSUE #104: Does this font support the UTF-8 subset for IBM437 symbols?
It's not clear from the README what glyphs and character sets this font supports. 
There are a lot of very useful symbols in UTF-8 and IBM437 that *should* be included, but not mentioned anywhere. Symbols for boxes, bullet points a check marks etc.

So what does it have?
* https://www.ascii-codes.com/
* https://en.wikipedia.org/wiki/Box-drawing_character

### LINKED ISSUE #125: Tilde ~ malformed (11pt)
# Environment

```none
Cascadia Code version number: 
Application (with version) used to display text: Visual Studio VS 2019 Prof. 16.3.1
OS platform and version: Win10 x64
Screen resolution (i.e. 220dpi): 2560x1440

Any other software?
```

# Steps to reproduce
image
virtual ~Foo();

# Expected behavior
Note: Expected behavior was achieved by changing the font from 11pt to 12pt.

image

# Actual behavior

image

### LINKED ISSUE #127: Feature Request: Support full Latin Core glyph set
# Description of the new feature/enhancement (with images if possible)

Google Fonts requires fonts to cover the [Latin Core](https://github.com/googlefonts/gftools/blob/master/Lib/gftools/encodings/GF%20Glyph%20Sets/GF-latin-core_unique-glyphs.nam) glyph set before they will consider adding a font.  Since Cascadia Code doesn't cover this, https://github.com/google/fonts/issues/2179 is currently on hold.  Since there are many requests for new glyphs, could this be used as a milestone to target?  I'd really like to see this font get added to Google Fonts, since Google's internal web IDE only pulls fonts from there, and you can't manually install fonts on ChromeOS.  Thanks!

### PR DESCRIPTION
**Pull request by aaronbell**
## Summary of the Pull Request
This update adds an extensive set of characters to Cascadia Code. Over 200 Latin languages now supported. 

## PR Checklist
* [x] Closes #11
Box drawing characters added.
* [x] Closes #29
Shifted position of slash characters for better alignment.
* [x] Closes #36
Glyph used for tick mark added (periodcentered). 
* [x] Closes #46
Length of == ligature extended. 
* [x] Closes #62
Case-sensitive forms removed in favor of single position forms. This enables more expected rendering.
* [x] Closes #104
Characters added.
* [x] Closes #125
Hinting on ~ forms updated.
* [x] Closes #127
Full Latin Core glyph set added.

* [x] CLA signed. If not, go over [here](https://cla.opensource.microsoft.com/microsoft/Terminal) and sign the CLA
* [x] Requires FONTLOG.txt to be updated
* [x] Requires [/images/cascadia-code.png](/microsoft/cascadia-code/blob/master/images/cascadia-code.png) and/or [/images/cascadia-code-characters.png](/microsoft/cascadia-code/blob/master/images/cascadia-code-characters.png) to be updated
* [x] I've discussed this with core contributors already. If not checked, I'm ready to accept this work might be rejected in favor of a different grand plan.

## Detailed Description of the Pull Request / Additional comments

All [language specific characters of Latin Plus](https://www.underware.nl/latin_plus/character_set/) as well as symbols in Win 1252, Box drawing characters, and other bits and bobs have been added. Additional small fixes here and there. Box drawing characters left unhinted for now :). 

Please also note that stylistic sets for the slashed zero, as well as changing the behavior for ~= have been added to the font. 

cascadia-code-characters

## Validation Steps Performed

Reviewed in Windows Terminal, VS Code, Edge, etc. 

If anyone is interested to test the font ahead, attached is a sample version of the updated font. PLEASE BE AWARE that this font is named "Cascadia Code Test". At this time, the version of Windows Terminal installs the older version of Cascadia Code that *cannot* be overriden. 

[CascadiaCode-TEST.ttf.zip](https://github.com/microsoft/cascadia-code/files/3668516/CascadiaCode-TEST.ttf.zip)

### CODE REVIEW

**Comment by aaronbell** [comment]
Thanks to @mdtauk for his help with the box drawing characters!

**Comment by aaronbell** [comment]
(also @madig this'll be the last Glyphs source :) )

**Comment by DHowett-MSFT** [comment]
I'm seeing a bit of an issue with ever-increasing numbers of hyphens:

image

**Comment by DHowett-MSFT** [comment]
Ah, this appears to happen for a bunch of repeated characters.

`>>>>`
image

`****`
image

`====`
image

**Comment by DHowett-MSFT** [comment]
The box-drawing characters, however, are utterly gorgeous.

image

**Comment by aaronbell** [comment]
@DHowett-MSFT Good catch! Looks like Glyphs auto-created substitution rules in the LIGA feature. I've turned it off and verified it is working properly now. New test file below. 

[CascadiaCode-TEST.ttf.zip](https://github.com/microsoft/cascadia-code/files/3668923/CascadiaCode-TEST.ttf.zip)

**Comment by DHowett-MSFT** [comment]
Excellent!

I've never seen this interpretation of a per-mille and I feel like it's totally in-character. I love it.
image

**Comment by DHowett-MSFT** [comment]
**Coverage**

* should non-breaking space (`U+00A0`) exist/be a copy of space? I can file a followup issue for this :smile:

**Comment by aaronbell** [comment]
Ah yes. Sometimes people want that character. Please do file a separate issue and we can pop it in :)

**Comment by DHowett-MSFT** [comment]
Here we go: https://github.com/microsoft/cascadia-code/issues/132

**Comment by ExE-Boss** [comment]
When is **Cascadia Code** getting a new release?

**Comment by cinnamon-msft** [comment]
@ExE-Boss Either today or tomorrow :)

**Comment by ExE-Boss** [comment]
@cinnamon-msft Will #132 be included in this release or the next?

I use non‑breaking spaces and hyphens quite a bit.

**Pull request merged**
