### PR TITLE
Fixing hinting on Braces

### LINKED ISSUE #595: Braces & their ligature variants not rendering properly in VS Code `#{` `}#` `{|` `|}` `{` `}`
### Cascadia family version

2110.31

### Cascadia family variant(s)

Cascadia Code (the version with ligatures), Cascadia Mono (the version without ligatures)

### Font file format(s)

.ttf (variable)

### Platform

Windows 10 Home

### Other Software

Visual Studio Code (portable edition)

### What happened?

Just freshly installed the new Cascadia variants, however the ligatures with the curly braces are not rendering properly in VS Code.  I'm using the variable TTF variants here. Regular TTF files work however. 

12px, medium:

2021-11-01 21_33_30-Visual Studio Code _ Notebook _ Trinity Language (new) md

21px, medium:

2021-11-01 21_34_16-Visual Studio Code _ Notebook _ Trinity Language (new) md

### PR DESCRIPTION
**Pull request by aaronbell**
## Summary of the Pull Request
When I updated the brace character, it appeared that the italic versions were rendering correctly. However, that was incorrect... 

They are rendering correctly now. 

## PR Checklist
* [x] Closes #595

### CODE REVIEW

**Comment by aaronbell** [comment]
Rebased so there's just the one change fixing the hinting

**Comment by DHowett** [comment]
Oof.

Point order change?

**Comment by aaronbell** [comment]
Yup. I checked in VTT, but it didn't show the issue initially, so I thought that the point orders were OK. Turns out not!

**Comment by DHowett** [comment]
Thanks for the fix!

**Comment by aaronbell** [comment]
Thanks! Sorry for the trouble

**Pull request merged**
