### PR TITLE
Updating README and other small fixes

### PR DESCRIPTION
**Pull request by aaronbell**
## Summary of the Pull Request

Updating the README page to better talk about font features, describe how to access the stylistic sets, and provide more information about the font front-and-center. Added some fun new images:

ligatures

arrow_support

stylistic_set

Additionally, located a few graphic glyphs with rotated components that have now been replaced with basic, non-rotated versions (no impact on rendering):

Screen Shot 2021-06-22 at 10 30 04 PM

### CODE REVIEW

**Comment by aaronbell** [comment]
Yikes that's a lot of commits—I forgot to do the commits to a branch. But the number of changed files are quite small!

**Comment by DHowett** [comment]
I love these images so much. Did you make them manually? Or is there some cool automated process we could put into our build system (not the same one that produces the fonts; a separate phase that consumes them!!

**Comment by aaronbell** [comment]
I made all of these (and actually the new character set images as well) using [Drawbot](https://www.drawbot.com), so we can definitely work them into the automated process. Heck, I can probably set it up so that the build script itself runs Drawbot.

That said, the ligature / arrow / stylistic set ones are built manually in Drawbot rather than being built on the fly (as in, based on what's actually in the font), so there's still some work to be done before they're super smart / powerful :).

**Comment by madig** [comment]
> Yikes that's a lot of commits

Use my old friend, `git rebase -i main` 😁

**Review by DHowett — APPROVED** [review]
*LOVE*

**Comment by madig** [comment]
The new stuff looks delicious 🍣

**Pull request merged**
