### PR TITLE
Bug fixes and other small improvements

### LINKED ISSUE #18: "7", "5" top strokes don't match thickness of those of "Z","E","F","T"
The horizontal strokes on the tops of `Z`, `F`, `E`, `T` are 190.0 units thick. On `7` it's 196.0 and on `5` it's 186.0.

At 12pt on a 96.0 DPI display (100% scaling), this results in a stroke with an unpleasantly high optical weight.

image
_(note: this repro image is 6pt on a 196.0-dpi display; it should act similar)_

**Source**: raw glyphs - not a hinting issue

### LINKED ISSUE #22: ligatures #[ and ]# have obvious height mismatches (with themselves and [ ])
12pt 96dpi -- not a hinting problem, reproduces at all scales

image

image

image

### LINKED ISSUE #30: The top curves of "s", "c" and "a" seem vertically compressed
The top curves of "s", "c" and "a" seem vertically compressed.

As a result the x-height of the words formed by these letters don't look balanced.

image

### LINKED ISSUE #38: 'W' and 'w' glyphs appear to be set too low
# Environment

Cascadia Code version number: version used in Sept 19 2019 blog post
Application (with version) used to display text: Mac Firefox 69 and Chrome 76
OS platform and version: MacOSX 10.13.6
Screen resolution (i.e. 220dpi): 220dpi

# Steps to reproduce

1. Load the blog post https://devblogs.microsoft.com/commandline/cascadia-code/
2. Look closely at the first subhead (“Wait, what’s Cascadia Code?”)
3. Note how the baseline of the ‘W’ and ‘w’ characters fit with the rest of the line

# Expected behavior

The baseline of the Ws should match the surrounding characters (particularly the ‘i’ and ‘h’)

# Actual behavior

The baseline of the Ws appears to be a pixel too low.

image

### LINKED ISSUE #64: Notch on curly brace is not very prominent (looks like parenthesis)
The notch on the curly brace is not very prominent (specifically at 14px size in Visual Studio Code on 4K display) which makes the curly brace look like a parenthesis. Since this font is targeting developers, I think more work should be done to differentiate these characters.

I think Fira Code does a better job in distinguishing parenthesis and curly brace and I am attaching screenshots for comparison.

**Cascadia Code:**
Cascadia Code

**Fira Code:**
Fira Code

### LINKED ISSUE #70: "Center dot" used for whitespace does not render properly.
# Environment

```none
Cascadia Code version number: 1909.16
Application (with version) used to display text: VS Code 1.38.1, Sublime Text 3.2.1
OS platform and version: Windows 10 1903
Screen resolution (i.e. 220dpi): 1440p

Any other software?
```

# Steps to reproduce

In VS Code, enable whitespace rendering and create a file with whitespace in it.

# Expected behavior

The whitespace dots appear in all programs that use them and display with proper spacing.
Annotation 2019-09-19 164306

# Actual behavior

In VS Code, the dots do not conform properly to the monospacing of the rest of the font. In other editors like Sublime Text, they show up as an invalid character block.

Annotation 2019-09-19 163530

Annotation 2019-09-19 164011

### LINKED ISSUE #71: ~= ligature
Same as [== ligature] #46 
The distinction between "=" and "~=" is quite subtle too.

### LINKED ISSUE #81: Height / distrib with parenthesis and brackets doesn't look quite right
# Environment
Cascadia Code version number: Cascadia Code 1909.16
Application (with version) used to display text: PHP Storm 2019.2
OS platform and version: Ubuntu 19
Screen resolution (i.e. 220dpi): 1920

# Steps to reproduce
Just typing similar

# Expected behavior
--

# Actual behavior
--

Hi! So I've trying the 1st release over my actual projects and I found this strange and a bit annoying detail.
Capture

by combining brackets along with parenthesis.
This, can be, maybe a potential improvement point (because of height/distribution difference).

See you!

### PR DESCRIPTION
**Pull request by aaronbell**
This is a general bug fix and character design update. 

## References
This update also includes a resolution covered by PR #27. 

## PR Checklist
* [X] Closes #18 
* [X] Closes #38 
* [X] Closes #30
* [X] Closes #70 
* [X] Closes #22 
* [X] Closes #81 
* [X] Closes #64 
* [X] Closes #71 
* [X] CLA signed
* [ ] Requires FONTLOG.txt to be updated
* [x] Requires [/images/cascadia-code.png](/microsoft/cascadia-code/blob/master/images/cascadia-code.png) and/or [/images/cascadia-code-characters.png](/microsoft/cascadia-code/blob/master/images/cascadia-code-characters.png) to be updated
* [x] I've discussed this with core contributors already. If not checked, I'm ready to accept this work might be rejected in favor of a different grand plan. Issue number where discussion took place: #xxx

## Detailed Description of the Pull Request / Additional comments
Changelist contained in this update:
- Updated 7 form (reduced top weight and sides to balance) Bug  #18 
Screen Shot 2019-09-21 at 10 06 02 AM

- Eliminated overshoot of v / w / V / W to appear more inline with baseline Bug #38 
- Adjusted top curve of c / S / C / G to be less ‘shiny’ Bug #30
Screen Shot 2019-09-21 at 10 13 27 AM

- Adjusted top curve of /a to be more in line with the x-height
Screen Shot 2019-09-21 at 10 14 43 AM

- Added center dot Bug #70 
- Added slashed zero as stylistic set 01
Screen Shot 2019-09-21 at 10 28 13 AM

- Added en and em dash
- Adjusted bracket positioning and hinting for more consistent rendering Bug #22 Bug #81 Bug #64
- Tweaked ~= shape Bug #71

All relevant hinting and code updated as well. 

## Before (if applicable) and After Images of the Character(s)
See above

## Validation Steps Performed
Updated font reviewed in Edge and VTT, as well as in software.

### CODE REVIEW

**Comment by ExE-Boss** [comment]
“Closes #18 #38 #30 #70 #22 #81 #64 #71” will only close #18.

To close all of them, [you need to write “closes” in front of all of them](https://help.github.com/en/articles/closing-issues-using-keywords).

**Comment by mdtauk** [comment]
Its good to see the actual Font designer in the GitHub!

Congratulations @aaronbell  on giving birth to this new typeface which we will all try to take care of as it grows up!

**Comment by vittau** [comment]
Shouldn't "_Requires /images/cascadia-code.png and/or /images/cascadia-code-characters.png to be updated_" be checked?

**Comment by ExE-Boss** [comment]
@vittau I asked pretty much the same question in https://github.com/microsoft/cascadia-code/pull/27#issuecomment-533213087.

**Comment by vittau** [comment]
> 
> 
> @vittau I asked pretty much the same question in [#27 (comment)](https://github.com/microsoft/cascadia-code/pull/27#issuecomment-533213087).

I see, thanks. Confusing checklist though. Is this one a draft PR as well?

**Comment by aaronbell** [comment]
@vittau @ExE-Boss I only got these changes pulled together this morning, so haven't had a chance to discuss with the team yet. That's why I haven't updated the images.

**Comment by alexhajdu** [comment]
Thanks for the update!

**Comment by seanmars** [comment]
Thanks for the update! Really good!

**Comment by madig** [comment]
This PR removed the explicit `gasp` table metadata. Is this intentional?

**Comment by aaronbell** [comment]
@madig Irritatingly, Glyphs doesn't allow the flexibility to set the `gasp` table as I want it to be. As such, to avoid confusion I'd removed it from the Glyphs file. You'll note that it is still present in the VTT source. 

This is a part of the process that could be improved via a code-driven workflow :)

**Comment by madig** [comment]
Ah, ok. The data looks like I can just store it in the UFO. Will add it to my PR.

**Comment by apianta** [comment]
How do we use the slash zero?

**Comment by cobrabr** [comment]
>Added slashed zero as stylistic set 01
How do I use this stylistic set?

**Comment by madig** [comment]
Depends on the application. See https://developer.mozilla.org/en-US/docs/Web/CSS/font-feature-settings, stylistic sets are "features" and go from `ss01`to `ss20`.

**Comment by chiniara** [comment]
Is it possible to get a TTF version with the slashed zero? 🤔

**Comment by apianta** [comment]
☝️☝️☝️

**Pull request merged**
