### PR TITLE
Better GDI treatment (among other things) 

### LINKED ISSUE #186: Odd Padding in VSCode Terminal (Xterm)
# Environment

```none
Cascadia Code version number: 1910.04
Application (with version) used to display text: vscode-insiders and vscode
OS platform and version: Windows 10 GA and Insiders
Screen resolution (i.e. 220dpi): Multiple monitors, multiple DPIs tested

Any other software?
```

# Steps to reproduce
1. Set "terminal.integrated.fontFamily": "Cascadia Code"
2. Open terminal
3. Use some characters that have a background color
4. There will be background padding at the bottom.

# Expected behavior
No additional padding below the lines

# Actual behavior
image
Note the padding at the bottom. No other font tested does this.

### LINKED ISSUE #274: Build environment: install vttLib from pypi?
It’s not clear why vttLib is installed from its git repository instead of the pypi packages.

### LINKED ISSUE #278: Cascadia Mono 16px height - frame drawing lines not connecting
# Environment

```none
Cascadia Code version number: 2005.15
Application (with version) used to display text: Native terminal
OS platform and version: Windows 7, Windows 10 1909
Screen resolution (i.e. 220dpi): DPI is a pixel density, NOT resolution.
20'' 1680×1050 LCD panel

Any other software?
```

# Steps to reproduce

Install font, register as candidate for terminal fonts, choose it in console properties at 16px height.

# Expected behavior

image

# Actual behavior

Veritcal lines are not connecting.
image

### PR DESCRIPTION
**Pull request by aaronbell**
## Summary of the Pull Request
This update is primarily focused on improving rendering quality of full-height characters, such as box drawing characters and PL characters. 

## PR Checklist
* [x] Closes #186 - with normalization of font metrics, PL glyphs should align better now. 
* [x] Closes #274 - requirements.txt file updated to pull the pypi version of vttlib
* [x] Closes #278 - height of line elements tall enough to account for older rendering environments
* [x] CLA signed. 

## Detailed Description of the Pull Request / Additional comments
GDI and DWrite versions of box drawing / PL characters now present in the font. Font uses `rclt` OpenType rule to swap from the default (GDI) ones to the DWrite versions. Heights of line box drawing characters also increased to account for GDI environments. Updated build process to replace .fea code to enable PL functionality. 

Other tweaks:
* Version numbers now explicitly set in build.py
* Corrected malforming IJacute diacritics
* Modified the underscore double to avoid clipping the bottom line
* Removed requirements.in, updated requirements.txt

## Before (if applicable) and After Images of the Character(s)
Capture3
PowerShell / Windows Terminal / VS Code

## Validation Steps Performed
Reviewed in emacs and Windows Terminal

### CODE REVIEW

**Comment by DHowett** [comment]
Merged the GDI changes (only) in 16c98b898c335bace62ab4c3ce2157bbcfd9a40d

**Comment by madig** [comment]
Why did you kill requirements.in, I just wanted to add something there :cry:

**Comment by aaronbell** [comment]
@madig use requirements.txt?

**Comment by madig** [comment]
Yes, but because subdependencies can change, it is recommended in Python land to keep the requirements.in file as the master from which a fresh requirements.txt file can be generated. Otherwise, you keep old subdeps no longer in use and new ones that are not pinned and as such are implicitly updated.

**Comment by aaronbell** [comment]
Fair enough. Previously the requirements.in file wasn't really being used (I think it has been empty for quite some time), so figured it could just be removed.

**Comment by madig** [comment]
Python packaging is hairy :o

**Pull request closed without merging**
