### PR TITLE
Strip date comments from CascadiaCode.ttx's VTT data

### PR DESCRIPTION
**Pull request by DHowett**
@aaronbell this is my proposal for stripping comments -- it's less intrusive than the changes ElementTree made, and it's a quick script any other contributors can use.

To use,

```
./stripVttComments.sh
```

That should be it.

If you agree with this approach, I can handle merging master into Nikolaus' branch to reduce the churn over there :smile:

### CODE REVIEW

**Comment by DHowett** [comment]
also, I see the value in the other comments that VTT emits; somebody who wants to look at the source and _actually understand what it's doing_ might want to keep them!

**Comment by DHowett** [comment]
(I'm afraid of the 13k line diff in the ttx in #365, so I wanted to pull it out and simplify it!)

**Comment by aaronbell** [comment]
It seems alright to me (and better to keep the glyph name comments), though I'd suggest also removing:
`/* GUI generated Sun Jun 28 08:35:23 2020 */`
`/* ACT generated Mon Sep 14 09:57:28 2020 */`

**Comment by DHowett** [comment]
Oh, good call!

**Comment by DHowett** [comment]
Got em!

**Pull request merged**
