### PR TITLE
Cascadia Code Upright bugfixes

### LINKED ISSUE #418: Bug: Top bar of Serbian Cyrillic capital Dje Ђ in bold is too thin
# Environment

```none
Cascadia Code version number: 2102.03
Application (with version) used to display text: any
OS platform and version: any
Screen resolution (i.e. 220dpi): any
```

# ~~Steps to reproduce~~

~~Put Ђ Ћ together in bold weight, now compare the two side by side. Notice the different widths of the top bars.~~

# Expected behavior 

Just a little bug/inconsistency i have to point out: In the bold weight, the top-bar of the Cyrillic Dje Ђ is thinner than that of Tshe Ћ. 

# Actual behavior

It renders like this in bold weight, and I'm sure this is because of interpolation, as the top bars in both letters are the same width in Regular and lighter weights.

### LINKED ISSUE #422: Add Bitcoin
Font is missing bitcoin symbol: ₿ (Unicode: U+20BF ₿ BITCOIN SIGN (HTML &#8383; ))

Split out of (#419)

### LINKED ISSUE #427: Add replacement character FFFD
Under the rare circumstances where Cascadia Code is used to render data that has an encoding issue, the replacement character � (uniFFFD) may be used instead of the `.notdef` character. It would be useful to add this glyph for such scenarios.

### LINKED ISSUE #433: Bug Report - Close square bracket misformed
# Environment

Cascadia Code version number:2102.025
Application (with version) used to display text:SQL Server Management Studio v15.0.18369.0
OS platform and version: Windows 10 v1909 (18363.1198)
Screen resolution (i.e. 220dpi): 96dpi

# Steps to reproduce

Set Environment Fonts and Colors, Font to Cascadia Mono, size 9.
A close square bracket ']' is misformed 

# Expected behavior

The close square brakcet should appear correctly.

# Actual behavior

The close square bracket is misformed on the upper corner.
FontIssue

The bracket display correctly at both 8 and 10 point settings.

### LINKED ISSUE #435: >>= ligature not working
# Environment

```none
Cascadia Code version number: 2102.003
Application (with version) used to display text: konsole 20.08.2
Also occurs when using:
    Visual Studio Code 1.55.0-insider 84fe402d655e029eb1a5c04e675bf64788fa7fcf x64
    gedit - Version 3.38.0
OS platform and version: Pop!_OS 20.10
Screen resolution (i.e. 220dpi):
    1920px×1080px
    344mm×194mm (96x96dpi)
```

# Steps to reproduce

Type `>>=`.

# Expected behavior

A ligature appears, as with `=<<`.

# Actual behavior

No ligature appears.

# Screenshot

Screenshot from 2021-03-22 14-50-02

### LINKED ISSUE #443: Feature Request: Remove the ligratures for *) symbol
# Description of the new feature/enhancement
When using the function pointer in C++ with VSCode, the asterisk will not be in the middle of the brackets. Especially when I am using the bracket colorizer plugin, the right bracket will not be colored to match the left bracket.
image

This also happens in my CLion, so it was not caused by VSCode

image

This problem won't appear when using other fonts that enable the ligatures
Fira Code:

image

JetBrains Mono:

image

### LINKED ISSUE #454: Bug Report (IF I DO NOT CHANGE THIS THE ISSUE WILL BE CLOSED)
# Environment
```none
Cascadia Code version number: 2102.25
Application (with version) used to display text: Visual Studio 2019 (16.9.4)
OS platform and version: Windows 10 (version 1909)
Screen resolution (i.e. 220dpi): 3440x1440 with DPI=100%
```

# Steps to reproduce
Install `CascadiaCode.ttf` (variable) for all users. Then, in Visual Studio simply type "===>" like this:

ligature-error

The artifact is only observed for **three** equal signs. Any other number produces a gap free arrow.

### LINKED ISSUE #467: VS Code doesn't recognize "Code PL" edition of the font but it recognize the "Cascadia Code".
# Environment

```none
Cascadia Code version number:
Application (with version) used to display text:
OS platform and version:
Screen resolution (i.e. 220dpi): 

Any other software?
```

# Steps to reproduce

# Expected behavior

# Actual behavior

### LINKED ISSUE #477: 2105.24 - Regular - bar_bar_equal_end.seq interpolation issue
Just for the halibut ... took a look at the Regular too.

Regular - 2021-05-26_11-03-33

### LINKED ISSUE #478: 2105.24 - Regular - dollar.BRACKET.600 interpolation issue
Same issue is in the Regular font.

### LINKED ISSUE #479: 2105.24 - Regular - less_less_hyphen_middle.seq interpolation issue
Regular - 2021-05-26_10-57-52

### LINKED ISSUE #480: 2105.24 - Regular - less_slash_greater.liga interpolation issue
In the Regular the advance width is changing - a lot.
The Italic is below for comparison.

**Regular**
Regular - 2021-05-26_10-48-09

**Italic**
Italic - 2021-05-26_10-51-23

OK, now I am _really_ done. ;-)

### LINKED ISSUE #481: No weigths in JetBrains 2021 typography settings panel
# Environment

```none
Cascadia Code version number: 2105.024
Application (with version) used to display text: Webstorm 2021.1.1
OS platform and version: Windows 10
Screen resolution (i.e. 220dpi): 4k/163dpi

Any other software?
```

# Expected behavior

Main weight and Bold weight dropdowns under the Typography Settings section should display all of the weigths

# Actual behavior

The panel shows only Roman weight
image

This is happening with the latest italics realease, so I'm guessing it's losing some info during the build step as it was working just fine prior to the update.

### PR DESCRIPTION
**Pull request by aaronbell**
## Summary of the Pull Request

A large set of bug fixes identified while working on the Italic, but solving Github reported issues. 

## PR Checklist
- [x] Closes #422 - Bitcoin added
- [x] Closes #427 - FFFD glyph added
- [x] Closes #418 - top bar corrected
- [x] Closes #433 - hinting corrected to ensure alignment
- [x] Closes #435 - adds consistent ligature form for `=>>` `<<=` `=<<` and `>>=` (the infinite arrows still work with addition of more equals)
- [x] Closes #443 - ligature now ignores (*) scenario
- [x] Closes #454 - adds ignore to prevent equal_equal ligature from showing up
- [x] Closes #467 - Not specifically sure of the problem here, but suspect that it will be fixed with this - update.
- [x] Closes #477 - fixed
- [x] Closes #478 - fixed
- [x] Closes #479 - fixed
- [x] Closes #480 - fixed
- [x] Closes #481 - JetBrains enumerates fonts weird. I've modified the internal naming so that it will register Cascadia Code correctly. Also aligned postscript naming with Google's recommendation, so will show up as "Regular" instead of "Roman". Still works in Word!

Other Cascadia Code fixes:
- General improvement of weight balancing
- Weight of lowercase rounds reduced in the Bold weight in Cascadia Code.
- Weight of Capital stems increased in Extralight weight in Cascadia Code. 
- Tweaked weight of ogonek in ExtraLight.
- Added a localized form for ĳ and Ĳ should a user chose to use those codepoints and want an accented version.
- Split fraction bar at heavier weights to improve clarity of fractions.
- Adjusted standard box drawing characters to align with GDI metrics, and added a complete set of DWrite-specific ones that align with sTypo (using `rclt`).
- Ironed out some tiny inconsistencies in the <$ $> <$> ligatures which I'm sure no one will ever notice. 
- Fixed centering of braces and some hyphens.
- Fixed inconsistency between semicolon/colon and period weight in bold. Also fixed slight differences in hyphen-like glyphs in bold. You're as surprised as I am. 
- Increased weight of underscore in bold.
- Adjusted weighting of Ɫ.
- Changed design of commaaccent, commaaccentmod commaturnedabove and commaabove to be more distinguishable (following design of quotes).
- Increased height of βδθλ to align with the ascender height. They were too low before. 
- Fixed descents of various greek lowercase glyphs that were inconsistent. 
- Modified ξ weighting. 
- Felt ligated, might edit later.
- Tweaked ªºⁿʷʸᶿᶻ⁰¹²³⁴⁵⁶⁷⁸⁹ in imperceptable ways. 
- Corrected some additional interpolation bugs

I do enjoy giving Dustin presents.

### CODE REVIEW

**Comment by aaronbell** [comment]
Also, remember friends, there are more fixes to come! So If you don't see yours yet, don't worry. I've got everything on the backlog :)

**Comment by DHowett** [comment]
>  Closes #477 - Not specifically sure of the problem here, but suspect that it will be fixed with this - update.
> Closes #477 - fixed

were these both supposed to be the same number?

**Comment by aaronbell** [comment]
Nope. :)

**Comment by DHowett** [comment]
>Felt ligated, might edit later.

_lol_

**Comment by DHowett** [comment]
Couple followup questions (sorry: I am out of my depth, and if my questions are annoying please let me know!)

* This introduces another `background` directory -- should we delete or keep for now?
* The changelog says it introduces the localized ij form, but it seems to be commenting out `lock_latin_2` (locl.fea) which I thought would remove it
* The changelog says it introduces rclt/stypo forms for the box drawing glyphs, but that code is also getting commented out in `rclt.fea`
   * It also _deletes_ the stypo versions of the box glyphs ("boxD_oubleD_ownA_ndH_orizontal.stypo.glif
**deleted file mode 100644**((**")

**Comment by DHowett** [comment]
UGH, Okay, ignore me. Only the `background` one is correct.

_I was looking at the diff the wrong way_. 19 years of software engineering and this is what I've done to myself.

Only the `background` question still stands. I realized that I thought your diff _deleted_ them, but then that clued me in that it was backwards and it is in fact _adding_ them.

**Comment by aaronbell** [comment]
👍 It happens! The background can be deleted. I usually clear them out of the source on my end but must have re-added some by accident.

**Comment by DHowett** [comment]
In that case, it does look like the .fea and .glif files are growing support for Hebrew and Arabic (there's a lot of them added in this PR)

**Comment by aaronbell** [comment]
Yup! All of that stuff is disabled for now. But once we have the rest of the bits ready I’ll turn it all back on.

**Comment by DHowett** [comment]
Oh this is great! Will the glyphs not even be included in the final font? This is so cool

**Comment by aaronbell** [comment]
Nope. They’ve been set as non-exporting.

**Pull request merged**
