### PR TITLE
Reduce the top stroke of the 7 to 190 units (from 196)

### LINKED ISSUE #18: "7", "5" top strokes don't match thickness of those of "Z","E","F","T"
The horizontal strokes on the tops of `Z`, `F`, `E`, `T` are 190.0 units thick. On `7` it's 196.0 and on `5` it's 186.0.

At 12pt on a 96.0 DPI display (100% scaling), this results in a stroke with an unpleasantly high optical weight.

image
_(note: this repro image is 6pt on a 196.0-dpi display; it should act similar)_

**Source**: raw glyphs - not a hinting issue

### PR DESCRIPTION
**Pull request by DHowett-MSFT**
## Summary of the Pull Request
This is a "dead reckoning" fix for #18. I do not have Glyphs, but if you compare `1420` and `1224` you get `196`, which is suspiciously identical to the height of the top stroke of the 7.

## PR Checklist
* [x] Closes #18
* [ ] Requires FONTLOG.txt to be updated
* [ ] Requires [/images/cascadia-code.png](/microsoft/cascadia-code/blob/master/images/cascadia-code.png) and/or [/images/cascadia-code-characters.png](/microsoft/cascadia-code/blob/master/images/cascadia-code-characters.png) to be updated
* [ ] I've discussed this with core contributors already. If not checked, I'm ready to accept this work might be rejected in favor of a different grand plan. Issue number where discussion took place: #xxx
* [ ] VTT file updated

## Detailed Description of the Pull Request / Additional comments
This is only a draft because I haven't adjusted the x coordinate fo the first point of the top stroke to intersect the rightmost stroke or updated the hinting data.

## Before (if applicable) and After Images of the Character(s)

(tbd)

## Validation Steps Performed

Manually adjusted the position of the points in another font editor and compared the resulting rendered text.

### CODE REVIEW

**Comment by DHowett-MSFT** [comment]
the X coordinate doesn't need to be updated to meet the diagonal stroke, as it was built overlapping.
I'll update the VTT file shortly.

**Comment by ExE-Boss** [comment]
Shouldn’t [/images/cascadia‑code‑characters.png](https://github.com/microsoft/cascadia-code/blob/master/images/cascadia-code-characters.png) be updated, since this affects the number `7`?

**Comment by DHowett-MSFT** [comment]
@ExE-Boss this is a draft PR, and the description calls out the need for me to update those images. The PR will be published for general review once it's actually ready.

**Comment by DHowett-MSFT** [comment]
## VTT screenshots

Grid fitting is turned on; this seems to accurately reproduce Visual Studio's rendering.

### Pixels

|original|new|
|-|-|
|image|image|

### ClearType

|OG|new|
|-|-|
|image|image|

### Grayscale

|o|new|
|-|-|
|image|image|

**Comment by DHowett-MSFT** [comment]
Superseded by #96

**Pull request closed without merging**
