### PR TITLE
Add Hebrew and Arabic; rework Italic

### LINKED ISSUE #84: support persian and arabic
I install Cascadia and i found unfortunately this font doesn't support Arabic and Persian.

### LINKED ISSUE #465: 2105.24 - Italic Style Groups and Font File Names Incorrect
The style groups are incorrect in the new Italic fonts.
This causes the all the Italic fonts to be in their own style group rather than linked with the related Regular.
Also causes the font file names to be confused.

And the Italic typographic family is also different.

### LINKED ISSUE #468: Option to use the old italic version
# Environment

```none
Cascadia Code version number: 2105.24
Application (with version) used to display text: vs code
OS platform and version: Windows 10 20H2
Screen resolution (i.e. 220dpi): 96dpi

Any other software?
```

# Steps to reproduce
The new italic font is hard to read
image

# Expected behavior
I would like to be able to use the old italic font.

# Actual behavior

### LINKED ISSUE #470: Some cursive lowercase glyphs appear to have a different slant than the others
# Environment

```none
Cascadia Code version number: 2105.24
Application (with version) used to display text: not relevant
OS platform and version: not relevant
Screen resolution (i.e. 220dpi): not relevant
```

# Steps to reproduce

1. Use Cascadia Code v2105.24
2. Write something that involves a lowercase L, lowercase Y, and possibly some others

# Expected behavior

A consistent slant for every glyph (except for block glyphs and similar "graphic" ones)

# Actual behavior

I will use this screenshot of a doc comment to illustrate:

image

In an attempt to highlight the differences in perceived slants I added vertical pipes between the lines, while forcing my editor to use a small line height.

So first of all, I want to acknowledge that this is somewhat subjective, and that I might be alone in "reading" these glyphs this way. Having said that, to me the cursive lowercase L feels almost straight. The other glyphs appear to "align" with the slanted vertical pipe characters above and below their lines (although the lowercase Y also appears a bit less slanted than the rest of the glyphs, but it's not as jarring). 

I know this is very nitpicky, and I don't want to criticize the designers of the cursive set - I think their design is cute overall, and I'm aware that font design is an art as much as a science, and more importantly that it's an incredible hassle to get it to "feel" just right. However, when quickly skimming text any cursive L's in the text really stand out a lot to me, kind of like how a single bold glyph among non-bold glyphs would stand out. They don't "disappear" into the whole word but break into individual characters, if that makes sense. And I think it's largely because of this difference in (perceived) slant.

(on a similar note the lowercase R breaks with the x-height in a way that makes `dendrogram` read a bit "wobbly", but that's probably overdoing the nitpicking)

### LINKED ISSUE #494: U+0192 is a lowercase letter and should visibly different from f in italic
### Cascadia family version

2105.24

### Cascadia family variant(s)

Cascadia Code (the version with ligatures), Cascadia Mono (the version without ligatures)

### Font file format(s)

Windows Terminal included version (TTF (variable)), .ttf (variable), .ttf (static), .otf (static), .woff2 (variable), .woff2 (static)

### Platform

Windows, Linux, macOS

### Other Software

_No response_

### What happened?

U+0192 ƒ in CascadiaCode-ExtraLight, -Regular or -Bold, is currently designed as a figure-height f with a hooked descender, it is shorter than f. In italic styles, It is not constructed as other letters.

Besides being encoded for the florin currency symbol or the function symbol, it is also encoded as the lowercase letter used along the uppercase U+0191 Ƒ in a few languages like Ewe, Avatime, Waci and Lelemi spoken in Benin, Ghana or Togo. These languages use it as an ascender-height f with a hooked descender.

## Roman styles
 
See the current roman U+0192 ƒ next to U+0066 f, where their height do not match:
image

U+0192 ƒ should instead match the height of U+0066 f in the roman styles.

## Italic styles

See the current roman U+0192 ƒ next to the proposed U+0066 f:
image

The current italic U+0192 ƒ is appropriate for those languages but has hooks that are more curved than those of j or ſ.  Additionaly the redesign of italic U+0066 f shown in https://github.com/microsoft/cascadia-code/issues/468#issuecomment-854196781 would make U+0192 ƒ and U+0066 f hard to dinguish as the only difference would how curved the hooks are or the slant of the stem slant.
This could be avoided with a straight descender or a flared descender instead of the hooked descender for U+0066 f.
The design of the italic U+0192 ƒ could stay the same but would be more appropriate with a stem on the same slant as other glyphs and the descender and ascender hooks as j and ſ.

U+0192 ƒ should be constructed like other letters, and U+0192 ƒ and U+0066 f should be identifiable and different.

## Extra bonus
It would be nice if U+0191 Ƒ, U+0189 Ɖ, U+0256 ɖ were in the fonts as most characters needed for those languages (including ƐɛƆɔƔɣŊŋƲʋ) are already present.

### LINKED ISSUE #499: Some below-base anchor points are too high
### Cascadia family version

2105.24

### Cascadia family variant(s)

Cascadia Code (the version with ligatures), Cascadia Mono (the version without ligatures)

### Font file format(s)

.ttf (variable), .ttf (static), .otf (static)

### Platform

macOS 10.14.6

### Other Software

_No response_

### What happened?

Some glyphs with descenders (including ones precomposed with below-base marks) have anchor points for below-base marks too high, such that the mark overlaps the descender.

Here is <U+0024, U+0051, U+0070, U+0071, U+0079, U+00A2, U+00FD, U+00FE, U+00FF, U+012F, U+0133, U+0173, U+0177, U+0233, U+0272, U+03B2, U+03BE, U+03C1, U+03CF, U+040F, U+0414, U+0426, U+0428, U+0434, U+0443, U+0446, U+0448, U+045E, U+045F, U+0496, U+0497, U+049A, U+049B, U+04A2, U+04A3, U+04AF, U+04B1, U+04B2, U+04B3, U+04B6, U+04B7, U+04EF, U+0E3F, U+1E8F, U+1E99, U+1EF3, U+1EF7, U+1EF9, U+20A1, U+20AB, U+20B2, U+20B5> with U+0331 COMBINING MACRON BELOW after each character. I may have missed some.
$̱Q̱p̱q̱y̱¢̱ý̱þ̱ÿ̱į̱ĳ̱ų̱ŷ̱ȳ̱ɲ̱β̱ξ̱ρ̱Ϗ̱Џ̱Д̱Ц̱Ш̱д̱у̱ц̱ш̱ў̱џ̱Җ̱җ̱Қ̱қ̱Ң̱ң̱ү̱ұ̱Ҳ̱ҳ̱Ҷ̱ҷ̱ӯ̱฿̱ẏ̱ẙ̱ỳ̱ỷ̱ỹ̱₡̱₫̱₲̱₵̱

### LINKED ISSUE #507: Italic version: make the vertical pipe character actually vertical
# Description of the new feature/enhancement (with images if possible)

Now that we have a dedicated glyph set for the italics, can we fix the fact that the vertical pipe is tilted like a forward slash?

image

- As you see, when italics are used the pipe looks awkward.
- Vertical pipes are used in circumstances where they are supposed to sort of connect vertically, e.g. in ASCII tables
- It's inconsistent with other orthogonal shapes, like dashes etc, which aren't tilted either
- The vertical pipe may now be mistaken for a forward slash (this actually happened to me when someone else was reading code from my screen)

### PR DESCRIPTION
**Pull request by aaronbell**
## Summary of the Pull Request

Major update! 

This update includes the brand new Arabic and Hebrew language coverage, along with a variety of bug fixes to the upright and italic fonts. There has also been a major overhaul of the Cascadia Code Italic lowercase to make the forms align better with our vision for the font. Enjoy :). 

Supersedes #491

## PR Checklist

Cascadia Code
* [x] Closes #84 - Arabic language support added!
* [x] Closes #465 - Hebrew language support added!
* [x] Closes #499 - Adjusted base mark positions / set others to be ignored in propagateAnchors

Cascadia Code Italic
* [x] Closes #470 - Adjusted slant on cursive forms to feel a bit better
* [x] Closes #468 - Moved cursive forms to `ss01` / `salt` feature 
* [x] Closes #507 - Changed bar / broken bar to be upright for better clarity. All ligature forms adjusted.

Both
* [x] Closes #494 - Adjusted `ƒ` in both upright and italic

## Detailed Description of the Pull Request / Additional comments

- Arabic (and Urdu) support added (design by Mohamad Dakak). See [the PDF](https://github.com/microsoft/cascadia-code/blob/main/doc/Arabic_KeyFeatures.pdf) for the exciting new Arabic ligature functionality used in Cascadia Code that gives the font greatly improved readability and feel more more akin to a text typeface. Don't want all that? Don't worry, Cascadia Mono will house a normal version of Arabic. 

Screen Shot 2021-06-17 at 11 31 13 AM

- Hebrew support added (design by Liron Lavi Turkenich)
Screen Shot 2021-06-17 at 11 31 45 AM

- Fixing a bug in the ccmp feature file and added ccmp to the feature set in the build script.
- Deleting the (unused) liga feature file
- Vika has reviewed and improved some forms in Cascadia Code upright. 
- /f, /l, /s, /r (and related forms) have been updated to follow more 'generic' forms. Previous versions have been moved to ss01 / salt OT features.

New default forms
Screen Shot 2021-06-16 at 11 32 46 AM

Cursive forms (`ss01` / `salt`)
Screen Shot 2021-06-16 at 11 33 34 AM

- Changed design of `ƒ` in upright to align better with the standard `f`. In the italic, the `ƒ` has been changed to follow the cursive version. When `ss01` is applied, the design of the `f` and `ƒ` are swapped, and if the `locl` EWE language setting is applied, the 'f' swaps for a straight descender version (with cursive `ƒ`). Complicated, but achieves supporting everything.
Screen Shot 2021-06-16 at 11 36 27 AM

- Entry and exit strokes across the italic lowercase have been rounded to better achieve the fun / playful design language that we intended for the italic. Other skeletons have been modified as necessary. Cyrillic has also been updated for better consistency with the new design. 
Screen Shot 2021-06-16 at 11 33 05 AM
Screen Shot 2021-06-17 at 11 39 50 AM

- Greek lowercase has been updated per feedback from Gerry Leonidas to be more cohesive (No longer a mix between a Monday and Friday font. All Friday, all the time)

old
Screen Shot 2021-06-16 at 11 38 49 AM

new
Screen Shot 2021-06-16 at 11 38 32 AM

## Validation Steps Performed
All updated reviewed, hinted, and reviewed again :)

### CODE REVIEW

**Comment by aaronbell** [comment]
Good luck @DHowett

**Comment by DHowett** [comment]
> Good luck @DHowett

That's the most ominous pull request invitation I've ever received.

**Comment by DHowett** [comment]
> Vika has reviewed and improved some forms in Cascadia Code upright.

Ooh, interested in what changed here!

> Monday ... Friday

I love these terms very much.

**Comment by aaronbell** [comment]
The changes were primarily made to the Bulgarian forms, and otherwise are pretty minor. 

For example:
Screen_Shot_2021-06-17_at_11_48_25_AM

Screen_Shot_2021-06-17_at_11_50_34_AM

Just some slight improvements to Cyrillic rendering.

**Comment by mdtauk** [comment]
@aaronbell  Thank you soo much for taking everyone's views on board, but still keeping the fun and playful feel of the italics that give Cascadia Code soooo much character!

italics image
These look so readable and yet still with flourish

Your efforts are appreciated from this guy here...

**Comment by DHowett** [comment]
One person I asked about the new italic (non-cursive) expressed a concern about the /l looking a bit un-`l`-like (in isolation). I wonder if it's related to it having a longer leftward stroke than `h` and `b` and letters with ascenders... or having one at all? But at the same time, I know that on an `l` it's _not_ an ascender and should not be given the same treatment.

I find that I'm always thrown off when I see the `l` in Source Code Pro:

image

Something about _that_ doesn't feel right to me, and I'm a bit reminded of it with our new one. I dunno. All in my head?

**Comment by aaronbell** [comment]
Hmmm. Possibly? That particular glyph gave me some struggles since it needs to be a bit wider than the entry strokes on the /b and /h (to fill space), but yeah, being too long looks weird (particularly in the lightest). Pulling it back a little would look a little like this:

Screen Shot 2021-06-17 at 3 26 16 PM

**Comment by DHowett** [comment]
I do think I like that more :) (I'll also ask the opinion of the other person who had a comment :))

Yeah -- it seems a hard one to get right!

**Comment by DHowett** [comment]
@aaronbell I'm ready to merge this if you are!

**Comment by aaronbell** [comment]
🚀🚀🚀🚀🚀

**Comment by DHowett** [comment]
you rock!

**Comment by aaronbell** [comment]
@DHowett Was wondering what the plan is to release this update :). I'm looking forward to folks being able to use the Arabic / Hebrew!

**Comment by DHowett** [comment]
Now that we're no longer holding back communication (and release notes and stuff) for the _recent announcements_, I'm hoping to have an update out shortly.
It's only harmed by the fact that Terminal may have to update as well. Ghhhhh

**Comment by aaronbell** [comment]
_may_ :)

Look forward to it!

**Pull request merged**
