### PR TITLE
April bug fixes

### LINKED ISSUE #159: @ looks like ©
# Description of the new feature/enhancement (with images if possible)
The @ symbol could easily be confused with the copyright symbol with the current design. Especially at smaller sizes, it looks a bit like a 'c' in an ellipse.
WindowsTerminal_9q9QPocUn1

While the copyright symbol is obviously a copyright symbol, the @ symbol is not obviously an @ symbol.

# Proposed technical implementation details (optional)
Separating the tail of the 'a' from the outline should eliminate any potential confusion, such as:
image

### LINKED ISSUE #199: Missing letters from Latin alphabet and IPA
Thanks for the good font! Yet, it can be even better :)

#33 was closed as done but the font is still missing a few things (including ones from the closed issue). I have this symbols in my texts and some of them are displayed with a box-placeholder, some are displayed with a symbol from another font that looks ugly.

The list of symbols I'd like to see eventually:

From Latin alphabet:

Ȟȟ - Latin capital/small letter H with caron (char codes: U+021E and U+021F) - it is used, e.g, in Lakota/Dakota texts. This symbol is displayed as a placeholder
Ǎǎ - Latin capital/small letter A with caron (char codes: U+01CD and U+01CE) - it is displayed with font substitution

From IPA (I have these symbols a lot in English dictionary sources and it would be great to get then in the font):

ɛ - U+025B LATIN SMALL LETTER OPEN E : epsilon
ʃ - U+0283 LATIN SMALL LETTER ESH
ʌ - U+028C LATIN SMALL LETTER TURNED V : caret, wedge
ʧ - U+02A7 LATIN SMALL LETTER TESH DIGRAPH
ɔ - U+0254 LATIN SMALL LETTER OPEN O
ʒ - U+0292 LATIN SMALL LETTER EZH : dram
ɪ - U+026A LATIN LETTER SMALL CAPITAL I

### LINKED ISSUE #201: Suggestion: set "Disable Last Change" in font custom parameters
# Description of the new feature/enhancement (with images if possible)

Glyphs keeps track of the date a glyph was last changed. This may be helpful when working outside Git, but this. Is. Git.

# Proposed technical implementation details (optional)

Set "Disable Last Change" in font custom parameters. This should strip out all keys like [here](https://github.com/microsoft/cascadia-code/compare/v1911.20...master#diff-6c6ec496dd121f02cb9d90d9045073d3R95-R96)

### LINKED ISSUE #202: Suggestion: remove or incorporate hinting assembly stored in some glyphs
# Description of the new feature/enhancement (with images if possible)

There seems to be assembly stored in some glyphs, like here: https://github.com/microsoft/cascadia-code/blob/d733599504811e8f3969de20368817d20e162dba/sources/CascadiaCode-Regular.ufo/glyphs/lowerL_eftQ_uadrantW_hiteC_ircle.glif#L48-L94
Nothing will be done with it by default. I wonder what put it there?

Files:
```
sources\CascadiaCode-Regular.ufo\glyphs\blackC_ircle.glif
sources\CascadiaCode-Regular.ufo\glyphs\blackD_iamond.glif
sources\CascadiaCode-Regular.ufo\glyphs\blackH_exagon.glif
sources\CascadiaCode-Regular.ufo\glyphs\blackH_orizontalE_llipse.glif
sources\CascadiaCode-Regular.ufo\glyphs\blackI_nW_hiteD_iamond.glif
sources\CascadiaCode-Regular.ufo\glyphs\blackL_argeC_ircle.glif
sources\CascadiaCode-Regular.ufo\glyphs\blackL_argeS_quare.glif
sources\CascadiaCode-Regular.ufo\glyphs\blackM_ediumD_iamond.glif
sources\CascadiaCode-Regular.ufo\glyphs\blackM_ediumD_ownT_riangleC_entred.glif
sources\CascadiaCode-Regular.ufo\glyphs\blackM_ediumL_eftT_riangleC_entred.glif
sources\CascadiaCode-Regular.ufo\glyphs\blackM_ediumL_ozenge.glif
sources\CascadiaCode-Regular.ufo\glyphs\blackM_ediumR_ightT_riangleC_entred.glif
sources\CascadiaCode-Regular.ufo\glyphs\blackM_ediumU_pT_riangleC_entred.glif
sources\CascadiaCode-Regular.ufo\glyphs\blackP_arallelogram.glif
sources\CascadiaCode-Regular.ufo\glyphs\blackP_entagon.glif
sources\CascadiaCode-Regular.ufo\glyphs\blackS_mallD_iamond.glif
sources\CascadiaCode-Regular.ufo\glyphs\blackS_mallL_ozenge.glif
sources\CascadiaCode-Regular.ufo\glyphs\blackS_mallS_quare.glif
sources\CascadiaCode-Regular.ufo\glyphs\blackS_quare.glif
sources\CascadiaCode-Regular.ufo\glyphs\blackV_erysmallS_quare.glif
sources\CascadiaCode-Regular.ufo\glyphs\blackV_erticalR_ect.glif
sources\CascadiaCode-Regular.ufo\glyphs\blackV_erticalE_llipse.glif
sources\CascadiaCode-Regular.ufo\glyphs\bottomH_alfB_lackC_ircle.glif
sources\CascadiaCode-Regular.ufo\glyphs\bottomH_alfB_lackD_iamond.glif
sources\CascadiaCode-Regular.ufo\glyphs\bullseye.glif
sources\CascadiaCode-Regular.ufo\glyphs\crosshatchF_illS_quare.glif
sources\CascadiaCode-Regular.ufo\glyphs\diagonalcrosshatchF_illS_quare.glif
sources\CascadiaCode-Regular.ufo\glyphs\dottedC_ircle.glif
sources\CascadiaCode-Regular.ufo\glyphs\dottedS_quare.glif
sources\CascadiaCode-Regular.ufo\glyphs\downB_lackS_mallT_riangle.glif
sources\CascadiaCode-Regular.ufo\glyphs\downB_lackT_riangle.glif
sources\CascadiaCode-Regular.ufo\glyphs\downW_hiteS_mallT_riangle.glif
sources\CascadiaCode-Regular.ufo\glyphs\downW_hiteT_riangle.glif
sources\CascadiaCode-Regular.ufo\glyphs\filledR_ect.glif
sources\CascadiaCode-Regular.ufo\glyphs\fisheye.glif
sources\CascadiaCode-Regular.ufo\glyphs\horizontalB_lackH_exagon.glif
sources\CascadiaCode-Regular.ufo\glyphs\horizontalF_illS_quare.glif
sources\CascadiaCode-Regular.ufo\glyphs\inverseB_ullet.glif
sources\CascadiaCode-Regular.ufo\glyphs\inverseW_hiteC_ircle.glif
sources\CascadiaCode-Regular.ufo\glyphs\largeC_ircle.glif
sources\CascadiaCode-Regular.ufo\glyphs\leftB_lackP_ointer.glif
sources\CascadiaCode-Regular.ufo\glyphs\leftH_alfB_lackC_ircle.glif
sources\CascadiaCode-Regular.ufo\glyphs\leftB_lackT_riangle.glif
sources\CascadiaCode-Regular.ufo\glyphs\leftB_lackS_mallT_riangle.glif
sources\CascadiaCode-Regular.ufo\glyphs\leftH_alfB_lackD_iamond.glif
sources\CascadiaCode-Regular.ufo\glyphs\leftH_alfB_lackS_quare.glif
sources\CascadiaCode-Regular.ufo\glyphs\leftH_alfB_lackW_hiteC_ircle.glif
sources\CascadiaCode-Regular.ufo\glyphs\leftW_hiteT_riangle.glif
sources\CascadiaCode-Regular.ufo\glyphs\leftW_hiteS_mallT_riangle.glif
sources\CascadiaCode-Regular.ufo\glyphs\leftW_hiteP_ointer.glif
sources\CascadiaCode-Regular.ufo\glyphs\lowerH_alfA_rc.glif
sources\CascadiaCode-Regular.ufo\glyphs\lowerH_alfI_nverseW_hiteC_ircle.glif
sources\CascadiaCode-Regular.ufo\glyphs\lowerH_alfB_lackW_hiteC_ircle.glif
sources\CascadiaCode-Regular.ufo\glyphs\lowerH_alfW_hiteS_quare.glif
sources\CascadiaCode-Regular.ufo\glyphs\lowerL_eftA_rc.glif
sources\CascadiaCode-Regular.ufo\glyphs\lowerL_eftB_lackT_riangle.glif
sources\CascadiaCode-Regular.ufo\glyphs\lowerL_eftH_alfW_hiteS_quare.glif
sources\CascadiaCode-Regular.ufo\glyphs\lowerL_eftQ_uadrantW_hiteC_ircle.glif
sources\CascadiaCode-Regular.ufo\glyphs\lowerL_eftT_riangle.glif
sources\CascadiaCode-Regular.ufo\glyphs\lowerR_ightD_iagonalH_alfB_lackS_quare.glif
sources\CascadiaCode-Regular.ufo\glyphs\lowerR_ightB_lackT_riangle.glif
sources\CascadiaCode-Regular.ufo\glyphs\lowerR_ightA_rc.glif
sources\CascadiaCode-Regular.ufo\glyphs\lowerR_ightQ_uadrantW_hiteC_ircle.glif
sources\CascadiaCode-Regular.ufo\glyphs\lowerR_ightT_riangle.glif
sources\CascadiaCode-Regular.ufo\glyphs\mediumB_lackS_quare.glif
sources\CascadiaCode-Regular.ufo\glyphs\mediumB_lackS_mallS_quare.glif
sources\CascadiaCode-Regular.ufo\glyphs\mediumW_hiteS_quare.glif
sources\CascadiaCode-Regular.ufo\glyphs\mediumW_hiteS_mallS_quare.glif
sources\CascadiaCode-Regular.ufo\glyphs\rightB_lackT_riangle.glif
sources\CascadiaCode-Regular.ufo\glyphs\rightB_lackS_mallT_riangle.glif
sources\CascadiaCode-Regular.ufo\glyphs\rightB_lackP_ointer.glif
sources\CascadiaCode-Regular.ufo\glyphs\rightH_alfB_lackC_ircle.glif
sources\CascadiaCode-Regular.ufo\glyphs\rightH_alfB_lackD_iamond.glif
sources\CascadiaCode-Regular.ufo\glyphs\rightH_alfB_lackS_quare.glif
sources\CascadiaCode-Regular.ufo\glyphs\rightH_alfB_lackW_hiteC_ircle.glif
sources\CascadiaCode-Regular.ufo\glyphs\rightW_hiteS_mallT_riangle.glif
sources\CascadiaCode-Regular.ufo\glyphs\rightW_hiteP_ointer.glif
sources\CascadiaCode-Regular.ufo\glyphs\rightW_hiteT_riangle.glif
sources\CascadiaCode-Regular.ufo\glyphs\topH_alfB_lackC_ircle.glif
sources\CascadiaCode-Regular.ufo\glyphs\topH_alfB_lackD_iamond.glif
sources\CascadiaCode-Regular.ufo\glyphs\topH_alfW_hiteS_quare.glif
sources\CascadiaCode-Regular.ufo\glyphs\topR_ightH_alfW_hiteS_quare.glif
sources\CascadiaCode-Regular.ufo\glyphs\upB_lackS_mallT_riangle.glif
sources\CascadiaCode-Regular.ufo\glyphs\upB_lackT_riangle.glif
sources\CascadiaCode-Regular.ufo\glyphs\upL_eftH_alfB_lackT_riangle.glif
sources\CascadiaCode-Regular.ufo\glyphs\upperH_alfA_rc.glif
sources\CascadiaCode-Regular.ufo\glyphs\upperH_alfB_lackW_hiteC_ircle.glif
sources\CascadiaCode-Regular.ufo\glyphs\upperH_alfI_nverseW_hiteC_ircle.glif
sources\CascadiaCode-Regular.ufo\glyphs\upperL_eftB_lackT_riangle.glif
sources\CascadiaCode-Regular.ufo\glyphs\upperL_eftD_iagonalH_alfB_lackS_quare.glif
sources\CascadiaCode-Regular.ufo\glyphs\upperlefttolowerrightF_illS_quare.glif
sources\CascadiaCode-Regular.ufo\glyphs\upperL_eftT_riangle.glif
sources\CascadiaCode-Regular.ufo\glyphs\upperL_eftW_hiteC_ircle.glif
sources\CascadiaCode-Regular.ufo\glyphs\upperL_eftA_rc.glif
sources\CascadiaCode-Regular.ufo\glyphs\upperL_eftQ_uadrantW_hiteC_ircle.glif
sources\CascadiaCode-Regular.ufo\glyphs\upperrighttolowerleftF_illS_quare.glif
sources\CascadiaCode-Regular.ufo\glyphs\upperR_ightA_rc.glif
sources\CascadiaCode-Regular.ufo\glyphs\upperR_ightB_lackC_ircle.glif
sources\CascadiaCode-Regular.ufo\glyphs\upperR_ightB_lackT_riangle.glif
sources\CascadiaCode-Regular.ufo\glyphs\upperR_ightT_riangle.glif
sources\CascadiaCode-Regular.ufo\glyphs\upperR_ightQ_uadrantW_hiteC_ircle.glif
sources\CascadiaCode-Regular.ufo\glyphs\upW_hiteT_riangle.glif
sources\CascadiaCode-Regular.ufo\glyphs\upW_hiteS_mallT_riangle.glif
sources\CascadiaCode-Regular.ufo\glyphs\upR_ightH_alfB_lackT_riangle.glif
sources\CascadiaCode-Regular.ufo\glyphs\upW_hiteT_riangleW_ithD_ot.glif
sources\CascadiaCode-Regular.ufo\glyphs\verticalF_illC_ircle.glif
sources\CascadiaCode-Regular.ufo\glyphs\verticalB_isectingL_ineW_hiteS_quare.glif
sources\CascadiaCode-Regular.ufo\glyphs\verticalF_illS_quare.glif
sources\CascadiaCode-Regular.ufo\glyphs\whiteB_ullet.glif
sources\CascadiaCode-Regular.ufo\glyphs\whiteC_ircle.glif
sources\CascadiaCode-Regular.ufo\glyphs\whiteD_iamond.glif
sources\CascadiaCode-Regular.ufo\glyphs\whiteH_exagon.glif
sources\CascadiaCode-Regular.ufo\glyphs\whiteL_argeS_quare.glif
sources\CascadiaCode-Regular.ufo\glyphs\whiteI_nB_lackS_quare.glif
sources\CascadiaCode-Regular.ufo\glyphs\whiteL_owerR_ightQ_uadrantS_quare.glif
sources\CascadiaCode-Regular.ufo\glyphs\whiteL_owerL_eftQ_uadrantS_quare.glif
sources\CascadiaCode-Regular.ufo\glyphs\whiteH_orizontalE_llipse.glif
sources\CascadiaCode-Regular.ufo\glyphs\whiteM_ediumD_iamond.glif
sources\CascadiaCode-Regular.ufo\glyphs\whiteM_ediumL_ozenge.glif
sources\CascadiaCode-Regular.ufo\glyphs\whiteP_arallelogram.glif
sources\CascadiaCode-Regular.ufo\glyphs\whiteP_entagon.glif
sources\CascadiaCode-Regular.ufo\glyphs\whiteR_ect.glif
sources\CascadiaCode-Regular.ufo\glyphs\whiteR_oundedC_ornersS_quare.glif
sources\CascadiaCode-Regular.ufo\glyphs\whiteS_mallL_ozenge.glif
sources\CascadiaCode-Regular.ufo\glyphs\whiteS_mallS_quare.glif
sources\CascadiaCode-Regular.ufo\glyphs\whiteS_quare.glif
sources\CascadiaCode-Regular.ufo\glyphs\whiteV_erticalE_llipse.glif
sources\CascadiaCode-Regular.ufo\glyphs\whiteU_pperR_ightQ_uadrantS_quare.glif
sources\CascadiaCode-Regular.ufo\glyphs\whiteU_pperL_eftQ_uadrantS_quare.glif
sources\CascadiaCode-Regular.ufo\glyphs\whiteV_erticalR_ect.glif
sources\CascadiaCode-Regular.ufo\glyphs\whiteV_erysmallS_quare.glif
```

# Proposed technical implementation details (optional)

Remove or incorporate into VTT dump?

### LINKED ISSUE #216: Rotate the tilde glyph to the usual position
Before I'll proceed with my feature request, let me say - thank you for this font, it is very legible and overall pleasant to use, especially after you included PowerLine characters :)

# Description

Font designer made a stylistic choice regarding tilde (`~`) glyph in Cascadia:

- Glyph is vertically centered (this is ok, great for a font designed for coding)
- Tilde is "rotated", to make glyph terminals parallel to the mean line (this is not ok, you wouldn't rotate any other glyph just to make it "more pleasant" to look at)

This is somewhat annoying and unexpected, especially since I see this glyph every single time I open my terminal emulator…

In other words, this is how it looks like right now:

cascadia-rotated-tilde

At larger size it does not look so bad, but at smaller size, the middle part of a tilde glyph ("bar") looks horizontal, making it look like some different character altogether.

And I would prefer if it looked somewhat like this:

tilde-good

Excuse my poor attempt here, I merely "rotated" back part of raster image. The point is to make the tilde look "balanced".

### LINKED ISSUE #221: Feature Request: Add dashed down and up arrow characters (⇣ and ⇡)
# Description of the new feature/enhancement (with images if possible)

Please add dashed down and up arrow characters (⇣ and ⇡), which are used by some shells by default for their git status prompts. For example: https://github.com/romkatv/powerlevel10k

At the moment my prompt looks like this:
image

For now I will switch the config to use the solid arrows

### LINKED ISSUE #222: Feature Request: 'NON‑BREAKING HYPHEN' (U+2011)
## Description of the new feature/enhancement

I use the non‑breaking hyphen in my commit messages when I intend to enforce where line‑breaks may not occur.

This makes my commit messages show boxes in place of non‑breaking hyphens.

### LINKED ISSUE #223: Feature Request: 'ONE DOT LEADER' (U+2024)
## Description of the new feature/enhancement

This&nbsp;character is&nbsp;used&nbsp;in [the&nbsp;output&nbsp;log of&nbsp;**TypeScript**&nbsp;tests](https://travis-ci.org/microsoft/TypeScript/jobs/630124454#L308-L356).

### LINKED ISSUE #230: Feature Request: 'PUNCTUATION SPACE' (U+2008)
# Description of the new feature/enhancement (with images if possible)

My custom regional settings use U+2008 PUNCTUATION SPACE as the thousands separator in numbers. Consolas and Fira Code display this as a regular space, so Cascadia displaying a replacement character in directory listings is very visible.

If a bit of scope creep is permitted, rather than patiently gathering individual requests for all the [whitespace characters](https://en.wikipedia.org/wiki/Whitespace_character), it may be worth just adding all the horizontal ones at once (mapping them to a regular space), as in "might not be correct spacing, but the best we can do in monospace, and certainly no worse than a replacement character".

### LINKED ISSUE #240: Latin small letter i with ogonek (012F) incorrectly handles Combining diactrical marks
# Environment

'''none
Cascadia Code version number: 1911.20
Application (with version) used to display text: Microsoft Word (ver. 2001 build 12430.20264 C2R) 
OS platform and version: Windows 10 Pro 18363.657
Screen resolution (i.e. 220dpi): 192dpi, 144dpi, 96dpi

Any other software?
'''

# Steps to reproduce

1. Type Latin small letter i with ogonek (012F) and any other letter after it.
2. Insert a combining diactrical mark after small letter i with ogonek (I've tried Unicode hex 0340, 341, 342).

# Expected behavior

The diactrical mark is rendered over latin small letter i with ogonek (012F).

# Actual behavior

The diactrical mark is rendered over the next letter but not over latin small letter i with ogonek.

### LINKED ISSUE #241: Feature Request: Ligatures for (* and *)
# Description of the new feature/enhancement (with images if possible)

`(*` and `*)` are used in many programming languages (including Modula-3, ML, Mathematica, Pascal, etc.) to delimit block comments.  I don’t see why they should be left out.

# Proposed technical implementation details (optional)

(none)

### LINKED ISSUE #252: Feature Request: Ligature for \\ (double backslash)
# Description of the new feature/enhancement

A ligature that replaces `\\` with a ligature that looks like a flipped version of the `//` ligature

### LINKED ISSUE #253: Feature Request: Ligature for "://" (scheme seperator and authority prefix in URIs)
# Description of the new feature/enhancement

A ligature for `://`  
This often appears in URLs.

### LINKED ISSUE #257: At 14px sub/super script numbers 1, 2, 4, and 7 do not appear to be horizontally aligned correctly and are slightly higher than the other numbers
# Environment

```none
Cascadia Code version number: 1911.210
Application (with version) used to display text: VS Code (1.44.2)
OS platform and version: Windows 10 (19613.1005)
Screen resolution (i.e. 220dpi): 1920x1080@141dpi (although this issue seems to be device independent)

Any other software?
```

# Steps to reproduce

Open VS Code and set the Font for the editor to Cascadia Code. 14 pixels is the default size for a VS Code editor window. Copy and paste the sub/super script numbers in the editor.

# Expected behavior

The sub/super script numbers should render at the same relevant foot and head heights as the standard numbers, at larger font sizes.

# Actual behavior

At 14px, subscript numbers (₀,₁,₂,₃,₄,₅,₆,₇,₈,₉) and superscript numbers (⁰,¹,²,³,⁴,⁵,⁶,⁷,⁸,⁹) appear to render with an appearance _similar_ to oldstyle figures. Using 0 as the baseline, the heads and feet of 1, 2, 4, and 7 appear to align above baseline while 3, 5, 6, 8, and 9 appear to be on the same baseline. Closer inspection at a higher point size, shows that this is this inconsistent with oldstyle figures in how the ascenders and descenders are supposed to be rendered, therefore they are _not_ oldstyle figures after all, but it doesn't change the fact that the rendering looks inconsistent at this point size compared with how they look at a larger point size.

### PR DESCRIPTION
**Pull request by aaronbell**
## Summary of the Pull Request
This update covers a number of small bug fixes from the last few months. 

## References
This encapsulates PR #226. 

## PR Checklist
* [x] Closes #202 – Unnecessary hinting instruction removed from imported glyphs
* [x] Closes #240 – Added additional diacritic glyphs, and modified ccmp to enable proper display of iogonek with diacritic above
* [x] Closes #199 - Additional IPA characters added
* [x] Closes #159 – Modified form of @ sign to better differentiate it from the ©
* [x] Closes #221 – ⇣⇡ added
* [x] Closes #222 - uni2011 added
* [x] Closes #223 - uni2024 added
* [x] Closes #230 - uni2008 added
* [x] Closes #241 - (* *) ligatures added
* [x] Closes #252 - \\\ ligature added
* [x] Closes #253 - :// ligature added
* [x] Closes #201 - 'Disable Last Change' feature cleaning out metadata from .glif
* [x] Closes #216 - THE RESQUIGGLING (all tilde forms reworked for more consistent and normalized forms)
* [x] Closes #257 - Correcting offset of subscript numerals 
* [x] Requires FONTLOG.txt to be updated - updated
* [x] CLA signed.

Additional bug fixes:
- Added 'top' anchors to some diacritics that were missing them
- Adjusted weight of descender on uni0497 for better consistency with other descenders
- Hinting added to above glyphs, and other glyph hinting corrected
- Updated several ligature glyph names for better consistency in feature code to avoid future issues. No change to glyph order

## Before (if applicable) and After Images of the Character(s)

Screenshot_4_29_20__3_44_PM

## Validation Steps Performed

Evaluated features in FontGoggles and text editors
Hinting modifications reviewed in VTT / browser

### CODE REVIEW

**Comment by DHowett-MSFT** [comment]
I'll handle producing the final build, if you'd like. I have that automatic pipeline that emits all the variants using your build script :smile: and hints them using vtt on Windows.

I'd like to hold off a bit to make sure Terminal can handle the line spacing (otherwise people getting upgrades will start to carp very loudly ☹️)

**Comment by aaronbell** [comment]
I was just sending you an email about that ;). But yeah, I figure it is better if y'all do the final build / releases as I know you have to take into consideration other requirements. 

Let me know when the line spacing is sorted—I'll need to make some fixes to the PL characters too, I'm guessing.

**Comment by DHowett-MSFT** [comment]
I'll let you know! Thanks

**Comment by DHowett-MSFT** [comment]
Weirdly, VTTshell is failing on this:

.\Microsoft.VTT.Tools.6.33.0\tools\vttshell.exe : Rasterizer error 0x140b: Incorrect MaxProfile entries for 
maxComponentElements and maxComponentDepth.


(Same version of VTT as you used o_O)

**Comment by aaronbell** [comment]
That's super weird. VTT is able to process it without problem. Does your VTTShell script do a "compile all" before trying to ship the font?

**Comment by DHowett-MSFT** [comment]
Yep, we're using `vttshell -a` which is the equivalent of "Compile All"

**Comment by DHowett-MSFT** [comment]
Interesting. If I use vtt directly and choose "ship font", it works. If I choose "compile everything for all glyphs", or "compile glyph programs for all glyphs", I get the same message but in a dialog:

image

**Comment by DHowett-MSFT** [comment]
This is the equivalent of a crazy person coming in and repainting the carpets, but if I click "recalculate maxp" before "compile all", it doesn't throw an error any longer.

**Comment by aaronbell** [comment]
That’s good! The maxp table is automatically generated anyway so is no problem. Probably just need to update (or remove?) the one in the TTX hinting file.

**Comment by DHowett-MSFT** [comment]
Alright, it looks like it can't be set to 0. VTT only updates it when it's _too high_.

https://github.com/microsoft/cascadia-code/pull/259

**Comment by DHowett-MSFT** [comment]
(It can't be deleted because the font authoring tools will carp about it)

**Comment by schuelermine** [comment]
I liked the old tildes more :(
Except for the `~~`. That looks undeniably better now.

**Comment by aaronbell** [comment]
Yeah, I figured it wouldn’t be to everyone’s tastes. The problem is that on lower resolution screens the old ~ could start to really look like a hyphen whereas the new one is unmistakable. Sometimes we have to bias towards usability over style!

**Comment by fitojb** [comment]
I am still heartbroken about the tilde.

**Pull request merged**
